[2024-07-14T17:49:57.676+0100] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pleaserun.get_news scheduled__2024-07-14T16:20:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
