[2024-07-14T13:03:36.069+0100] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pleaserun.get_sentiments scheduled__2024-07-14T11:50:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
